// apps/angular/src/app/pages/notes/ui/note-list.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core'
import { Note } from '../types/notes'
import { NoteItem } from './note-item'

@Component({
  selector: 'playground-note-list',
  imports: [NoteItem],
  template: `
    @if (notes().length === 0) {
      <p className="mt-4 text-center">No tasks yet. Add one!</p>
    } @else {
      <ul class="mt-4">
        @for (note of notes(); track note.id) {
          <li>
            <playground-note-item
              [note]="note"
              (onToggle)="onToggle.emit($event)"
              (onDelete)="onDelete.emit($event)"
              (onEdit)="onEdit.emit({ id: $event.id, title: $event.title })"
            />
          </li>
        }
      </ul>
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NoteList {
  notes = input.required<Note[]>()

  onToggle = output<{ id: number, completed: boolean }>()
  onDelete = output<number>()
  onEdit = output<{ id: number, title: string }>()
}

// apps/react/src/app/notes/ui/NoteList.tsx
import React from 'react'
import { Note } from '../types/notes'
import { NoteItem } from './NoteItem'

type Props = {
  notes: Note[]
  onToggle: (payload: { id: number, completed: boolean }) => void
  onDelete: (id: number) => void
  onEdit: (payload: { id: number, title: string }) => void
}

export const NoteList: React.FC<Props> = ({
  notes,
  onToggle,
  onDelete,
  onEdit,
}) => {
  if (notes.length === 0) {
    return <p className="mt-4 text-center">No tasks yet. Add one!</p>
  }

  return (
    <ul className="mt-4">
      {notes.map(note => (
        <NoteItem
          key={note.id}
          note={note}
          onToggle={onToggle}
          onDelete={onDelete}
          onEdit={onEdit}
        />
      ))}
    </ul>
  )
}
