// apps/svelte/src/routes/notes/ui/NoteList.svelte
<script lang='ts'>
  import type { Note } from '../types/notes'
  import NoteItem from './NoteItem.svelte'

  type Props = {
    notes: Note[]
    onToggle: (payload: { id: number, completed: boolean }) => void
    onDelete: (id: number) => void
    onEdit: (payload: { id: number, title: string }) => void
  }

  const { notes, onToggle, onDelete, onEdit }: Props = $props()
</script>

{#if notes.length === 0}
  <p class='mt-4 text-center'>No tasks yet. Add one!</p>
{:else}
  <ul class='mt-4'>
    {#each notes as note (note.id)}
      <NoteItem
        {note}
        {onToggle}
        {onDelete}
        {onEdit}
      />
    {/each}
  </ul>
{/if}

// apps/react/src/app/notes/ui/NoteList.tsx
import React from 'react'
import { Note } from '../types/notes'
import { NoteItem } from './NoteItem'

type Props = {
  notes: Note[]
  onToggle: (payload: { id: number, completed: boolean }) => void
  onDelete: (id: number) => void
  onEdit: (payload: { id: number, title: string }) => void
}

export const NoteList: React.FC<Props> = ({
  notes,
  onToggle,
  onDelete,
  onEdit,
}) => {
  if (notes.length === 0) {
    return <p className="mt-4 text-center">No tasks yet. Add one!</p>
  }

  return (
    <ul className="mt-4">
      {notes.map(note => (
        <NoteItem
          key={note.id}
          note={note}
          onToggle={onToggle}
          onDelete={onDelete}
          onEdit={onEdit}
        />
      ))}
    </ul>
  )
}
