// apps/svelte/src/routes/notes/ui/NoteInput.svelte
<script lang='ts'>
  type Props = {
    onAdd: (title: string) => void
  }

  const { onAdd }: Props = $props()

  let value = $state('')

  function handleSubmit(event: Event) {
    event.preventDefault()
    const trimmed = value.trim()
    if (!trimmed)
      return
    onAdd(trimmed)
    value = ''
  }
</script>

<form onsubmit={handleSubmit} class='flex gap-2'>
  <input
    type='text'
    bind:value={value}
    name='note-input'
    placeholder='Add a new task...'
    class='flex-1 rounded-lg border px-3 py-2'
  />
  <button type='submit' class='bg-accent rounded-lg px-4 py-2'>
    Add
  </button>
</form>

// apps/angular/src/app/pages/notes/ui/note-input.ts
import { ChangeDetectionStrategy, Component, output, signal } from '@angular/core'
import { FormsModule } from '@angular/forms'

@Component({
  selector: 'playground-note-input',
  imports: [FormsModule],
  template: `
    <form (ngSubmit)="handleSubmit()" class="flex gap-2">
      <input
        type="text"
        [(ngModel)]="value"
        name="note-input"
        placeholder="Add a new task..."
        class="flex-1 rounded-lg border px-3 py-2"
      />
      <button
        type="submit"
        class="rounded-lg px-4 py-2 bg-accent"
      >
        Add
      </button>
    </form>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NoteInput {
  value = signal('')

  onAdd = output<string>()

  handleSubmit(): void {
    const trimmed = this.value().trim()
    if (!trimmed)
      return
    this.onAdd.emit(trimmed)
    this.value.set('')
  }
}
